version: "3.5"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST: "0.0.0.0"
      POSTGRES_PORT: 5432
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network
  go:
    build:
      context: .
    depends_on:
      - "db"
    ports:
      - "3000:3000"
    links:
      - db
    networks:
      - app-network
    restart: always
volumes:
  dbdata:
networks:
  app-network:
    driver: bridge